const { v4: uuidv4 } = require("uuid");

let DatosPet = {
  // Cats
  cats: [
    {
      id: uuidv4(),
      nombre: "Polo",
      dueño: "Jackie",
      especie: "Gato",
      raza: "Criollo",
      fechaNacimiento: "2022-04-01",
      edad: "2 años",
      diagnosticos: "Alergia estacional",
      tratamientosPrevios: "Antihistamínicos",
      vacunas: "Vacunado contra panleucopenia, herpesvirus y calicivirus.",
      alergias: "Polvo y polen",
      imagen: "/uploads/cat.jpg",
    },
    {
      id: uuidv4(),
      nombre: "Galileo",
      dueño: "Jose",
      especie: "Gato",
      raza: "Criollo",
      fechaNacimiento: "2021-04-01",
      edad: "3 años",
      diagnosticos: "Estomatitis",
      tratamientosPrevios: "Limpieza dental y tratamiento con antibióticos.",
      vacunas: "Completas",
      alergias: "Ninguna conocida",
      imagen: "/uploads/cat1.jpg",
    },
    {
      id: uuidv4(),
      nombre: "Felix",
      dueño: "Jose",
      especie: "Gato",
      raza: "Criollo",
      fechaNacimiento: "2022-04-01",
      edad: "1 años",
      diagnosticos: "Giardiasis",
      tratamientosPrevios: "Desparasitante",
      vacunas: "Vacunado contra panleucopenia y rabia",
      alergias: "Ninguna conocida",
      imagen: "/uploads/cat2.jpg",
    },
    {
      id: uuidv4(),
      nombre: "Buñuelo",
      dueño: "Maria",
      especie: "Gato",
      raza: "Criollo",
      fechaNacimiento: "2022-04-01",
      edad: "1 años",
      diagnosticos: "Obesidad leve",
      tratamientosPrevios: "Dieta controlada y aumento de actividad física",
      vacunas: "Completas",
      alergias: "Ninguna conocida",
      imagen: "/uploads/cat3.jpg",
    },
  ],
  // Dogs
  dogs: [
    {
      id: uuidv4(),
      nombre: "Max",
      dueño: "Carlos",
      especie: "Perro",
      raza: "Labrador",
      fechaNacimiento: "2020-06-15",
      edad: "4 años",
      diagnosticos: "Ninguno",
      tratamientosPrevios: "Vacuna anual",
      vacunas: "Completas",
      alergias: "Ninguna conocida",
      imagen: "/uploads/dog.jpg",
    },
    {
      id: uuidv4(),
      nombre: "Luna",
      dueño: "Maria",
      especie: "Perro",
      raza: "Pastor Aleman",
      fechaNacimiento: "2021-03-10",
      edad: "3 años",
      diagnosticos: "Ninguno",
      tratamientosPrevios: "Desparasitación",
      vacunas: "Completas",
      alergias: "Sensible a ciertos alimentos",
      imagen: "/uploads/dog1.jpg",
    },
  ],

  // Exotic Pets
  exotics: [
    {
      id: uuidv4(),
      nombre: "Rex",
      dueño: "Pedro",
      especie: "Exotico",
      raza: "Huron",
      fechaNacimiento: "2022-01-20",
      edad: "2 años",
      diagnosticos: "Ninguno",
      tratamientosPrevios: "Chequeo anual",
      vacunas: "Aplicadas",
      alergias: "Ninguna conocida",
      imagen: "/uploads/exotic.jpg",
    },
  ],
};

module.exports = DatosPet;
